### PR TITLE
Support blueprint version upgrades

### PR DESCRIPTION
**Pull request by thecodesmith**
This PR implements the `rendr upgrade` command. It also enables specifying
upgrade scripts in the blueprint metadata file like this:

    upgrades:
    - version: 2
      script: upgrade-v2.groovy
      executable: rendr-sdk-groovy

The `upgrade` command will run any upgrade scripts specified (or skip if there are none).
In addition, it will render the templates for any files that do no exist yet.

The logic looks like this:
- Render templates for any files that do not exist in the target project
- Run any upgrade scripts specified in the `metadata.yaml`
- Set the `version` key to the new blueprint version in the project's `.rendr.yaml` file

There are some limitations currently:
- [Implemented!] Values are not yet passed to the upgrade scripts
- Projects cannot yet specify a particular blueprint version to upgrade to,
  only use the latest

### CODE REVIEW

**Comment by thecodesmith** [comment]
I will say, the code on this is... potentially garbage. But it is functional, I think. I wrestled for a long time with HashMaps containing strings being passed around...

**Comment by uint-jamf** [comment]
It looks good to me for now, though I'm definitely thinking one day we'll have to refactor the whole project to make everything DRYer and more comprehensive.

I'm going to test how it works tomorrow, along with the groovy SDK.

**Comment by uint-jamf** [comment]
In particular, I'd love to have one data structure that represents values, and one data structure that just represents a whole generated project. Then we can have one place where those things are parsed and validated and so on.

**Comment by uint-jamf** [comment]
By the way, I'm not really picking at your PR exactly, just at the need to take care of the growing project. Your PR LGTM.

**Comment by thecodesmith** [comment]
@uint-jamf With your template upgrade branch being merged first, there are some conflicts now on this branch. Most of them were straightforward, but I got stuck converting my new functionality to use the `Values` struct you introduced. If you have time to take a stab at it, that would be... fantastic. If not, that is fine, I can work through it tomorrow.

**Comment by uint-jamf** [comment]
@thecodesmith First of all, sorry. I ended up doing too much in that other PR. Shouldn't have changed something crosscutting like that. Totally on me.

I got it working on the `support-upgrade-scripts-rebase` branch. I figured it'd be better if you double-check it on a separate branch, so I didn't want to force push it here.

We could force push it here and merge, or just merge from that other branch!

**Comment by thecodesmith** [comment]
Awesome, thanks for the help! I will check it out and we can merge it from there!

**Comment by thecodesmith** [comment]
Closing this out in favor of this PR: https://github.com/jamf/rendr/pull/19.

**Pull request closed without merging**
